
logging:

  # path to a file where cli logs will be saved.
  filename: {{ log_path }}

  # configuring level per logger
  loggers:

    # main logger of the cli. provides basic descriptions for executed operations.
    aria.cli.main: info

  execution:
    formats:
      # According to verbosity level 0 - no verbose. 3 - high verbose
      0: '{message}'
      1: '{timestamp:%H:%M:%S} | {level[0]} | {message}'
      2: '{timestamp:%H:%M:%S} | {level[0]} | {implementation} | {message}'
      3: '{timestamp:%H:%M:%S} | {level[0]} | {implementation} | {inputs} | {message}'

    colors:
      enabled: true

      level:
        default: {'fore': 'lightmagenta_ex'}
        error: {'fore': 'red', 'style': 'bright'}
      timestamp:
        default: {'fore': 'lightmagenta_ex'}
        error: {'fore': 'red', 'style': 'bright'}
      message:
        default: {'fore': 'lightblue_ex'}
        error: {'fore': 'red', 'style': 'bright'}
      implementation:
        default: {'fore': 'lightblack_ex'}
        error: {'fore': 'red', 'style': 'bright'}
      inputs:
        default: {'fore': 'blue'}
        error: {'fore': 'red', 'style': 'bright'}
      traceback:
        default: {'fore': 'red'}

      marker: 'lightyellow_ex'
